@url = http://localhost:3000

###############################################
# admin Controller
###############################################

### Get all admins
GET {{url}}/admin


### Get admin by ID
GET {{url}}/admin/9

### Create new admin
POST {{url}}/admin
Content-Type: application/json

{
    "id": 13,
   "username": "Abigayle.Schaefer",
    "last_login": "2025-06-10",
    "createdAt": "2025-06-10T11:12:29.040Z",
    "updatedAt": "2025-06-10T11:12:29.040Z",
    "password": "Password123",
    "email": "ambale@gmail.com"
}

### Update admin
PATCH {{url}}/admin/3
Content-Type: application/json

{
"id": 9,
  "username": "Garret_Davis",
  "last_login": "2025-06-10",
  "createdAt": "2025-06-10T11:12:30.676Z",
  "updatedAt": "2025-06-10T11:12:30.676Z"
}

### Delete admin
DELETE {{url}}/admin/1

###############################################
# users Controller
###############################################

### Get all users
GET {{url}}/user

### Get all students with search
GET {{url}}/user?search=Carrie.Kiehn12

### Get users by ID
GET {{url}}/user/65

### Create new user
POST {{url}}/user
Content-Type: application/json

{
  "userid": 65,
    "username": "Eliza_Johnson",
    "password": "AA5x6AhVzVtcxx1",
    "email": "Felicita_Hoeger@yahoo.com",
    "refreshToken": null,
    "last_login": "2025-06-09T17:03:31.984Z",
}

### Update user
PATCH {{url}}/user/65
Content-Type: application/json

{
   "userid": 65,
    "username": "Eliza_Johnson",
    "password": "AA5x6AhVzVtcxx1",
    "email": "Felicita_Hoeger@yahoo.com",
    "refreshToken": null,
    "last_login": "2025-06-09T17:03:31.984Z"
}

### Delete user
DELETE {{url}}/user/65

###############################################
# Student Controller
###############################################

### Get all students
GET {{url}}/students

### Get student by ID
GET {{url}}/students/4

### Create new student
POST {{url}}/students/
Content-Type: application/json

{
  "id": 5,
  "room_id": 3,
  "course_id": 2,
  "registration_date": 2024
}

### Update student
PATCH {{url}}/students/1
Content-Type: application/json

{
  "id": 4,
  "room_id": 3,
  "course_id": 2,
  "registration_date": "2024-09-25T02:11:25.054Z"
}

### Delete student
DELETE {{url}}/students/4

###############################################
# Complain Controller
###############################################

### Get all complains
GET {{url}}/complains

### Get complain by ID
GET {{url}}/complains/1

### Create new complain
POST {{url}}/complains
Content-Type: application/json

{
  "title": "Leaky Faucet",
  "description": "The faucet in room 102 is leaking constantly.",
  "studentId": 2
}

### Update complain
PATCH {{url}}/complains/1
Content-Type: application/json

{
  "title": "Broken Faucet",
  "description": "The faucet has now broken completely."
}

### Delete complaint
DELETE {{url}}/complaints/1

###############################################
# Feedback Controller
###############################################

### Get all feedback
GET {{url}}/feedback

### Get feedback by ID
GET {{url}}/feedback/1

### Create feedback with complaint associations
POST {{url}}/feedback
Content-Type: application/json

{
  "message": "Issue was resolved quickly.",
  "studentId": 2,
  "complaintIds": [1, 2]
}

### Update feedback
PATCH {{url}}/feedback/1
Content-Type: application/json

{
  "message": "Thank you for the quick fix!",
  "complaintIds": [1]
}

### Delete feedback
DELETE {{url}}/feedback/1

### Get all feedback for a student
GET {{url}}/student/2/feedback

### Get all feedback associated with a complaint
GET {{url}}/complain/1/feedback




###############################################
# AUTHENTICATION
###############################################
### SIGNUP a new user
POST {{url}}/auth/signup

{
 "password": "ambale",
  "email":"ambale@gmail.com"
}
### LOGIN a new user
POST {{url}}/auth/signin
Content-Type: application/json

{
 "password":"admin123",
  "email":"stuart14@hotmail.com"
}
### REGISTER a new user
### Create new a new student profile
POST {{url}}/users
Content-Type: application/json

{
  "room_id": 10,
  "first_name": "John",
  "last_name": "Doe",
  "phone_number": "1234567890",
  "address": "not-an-email",
  "course_id": 1,
  "registration_date": 2025-05-25

}


### Create new a new admin profile
POST {{url}}/users
Content-Type: application/json

{

}

### signout
GET {{url}}/auth/signout/1

###############################################
# Authorized requests
###############################################
@AccessToken =place your access token here
@RefreshToken = place your refresh token here
GET {{url}}/profile
Authorization: Bearer {{AccessToken}}

###
### Get all students
GET {{url}}/students
Authorization: Bearer {{AccessToken}}

### refresh token
GET {{url}}/auth/refresh?id=9
Authorization: Bearer {{RefreshToken}}

